version: "3.7"
services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - "./data/redis-dbonly:/data"

  mongo:
    image: mvertes/alpine-mongo
    hostname: mongo
    container_name: mongo
    volumes:
      - ./data/mongodb-dbonly:/data/db
    command: mongod --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27017:27017
    restart: always