export const chainList = {
    1: {
        name: "Ethereum Mainnet",
        chain: "ETH",
        icon: "ethereum",
        rpcUrls: {
            infura: "https://mainnet.infura.io/v3/${INFURA_API_KEY}",
            wss: "wss://mainnet.infura.io/ws/v3/${INFURA_API_KEY}",
            // default: "https://api.mycryptoapi.com/eth",
            default: "https://cloudflare-eth.com",
        },
        rpc: [
            "https://mainnet.infura.io/v3/${INFURA_API_KEY}",
            "wss://mainnet.infura.io/ws/v3/${INFURA_API_KEY}",
            "https://api.mycryptoapi.com/eth",
            "https://cloudflare-eth.com",
        ],
        faucets: [],
        nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
        infoURL: "https://ethereum.org",
        shortName: "eth",
        chainId: 1,
        networkId: 1,
        slip44: 60,
        ens: { registry: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e" },
        explorers: [
            { name: "etherscan", url: "https://etherscan.io", standard: "EIP3091" },
        ],
        blockExplorers: {
            default: {
                name: "etherscan",
                url: "https://etherscan.io",
                standard: "EIP3091",
            },
        },
        id: 1,
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
        wrapped: { address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" },
    },
    4: {
        name: "Rinkeby",
        title: "Ethereum Testnet Rinkeby",
        chain: "ETH-R",
        network: "testnet",
        rpcUrls: { default: "https://rinkeby.infura.io/v3/" },
        rpc: [
            "https://rinkeby.infura.io/v3/${INFURA_API_KEY}",
            "wss://rinkeby.infura.io/ws/v3/${INFURA_API_KEY}",
        ],
        faucets: [
            "http://fauceth.komputing.org?chain=4&address=${ADDRESS}",
            "https://faucet.rinkeby.io",
        ],
        nativeCurrency: { name: "Rinkeby Ether", symbol: "RIN", decimals: 18 },
        infoURL: "https://www.rinkeby.io",
        shortName: "rin",
        chainId: 4,
        networkId: 4,
        ens: { registry: "0xe7410170f87102df0055eb195163a03b7f2bff4a" },
        explorers: [
            {
                name: "etherscan-rinkeby",
                url: "https://rinkeby.etherscan.io",
                standard: "EIP3091",
            },
        ],
        blockExplorers: {
            default: {
                name: "etherscan-rinkeby",
                url: "https://rinkeby.etherscan.io",
                standard: "EIP3091",
            },
        },
        id: 4,
        wrapped: { address: "0xDf032Bc4B9dC2782Bb09352007D4C57B75160B15" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    5: {
        name: "Goerli",
        title: "Ethereum Testnet Goerli",
        chain: "ETH-G",
        network: "testnet",
        rpcUrls: {
            public: "https://goerli.infura.io/v3",
            default: "https://rpc.goerli.mudit.blog/",
        },
        rpc: ["https://goerli.infura.io/v3", "https://rpc.goerli.mudit.blog/"],
        faucets: [
            "http://fauceth.komputing.org?chain=5&address=${ADDRESS}",
            "https://goerli-faucet.slock.it?address=${ADDRESS}",
            "https://faucet.goerli.mudit.blog",
        ],
        nativeCurrency: { name: "Goerli Ether", symbol: "GOR", decimals: 18 },
        infoURL: "https://goerli.net/#about",
        shortName: "gor",
        chainId: 5,
        networkId: 5,
        ens: { registry: "0x112234455c3a32fd11230c42e7bccd4a84e02010" },
        explorers: [
            {
                name: "etherscan-goerli",
                url: "https://goerli.etherscan.io",
                standard: "EIP3091",
            },
        ],
        blockExplorers: {
            default: {
                name: "etherscan-goerli",
                url: "https://goerli.etherscan.io",
                standard: "EIP3091",
            },
        },
        id: 5,
        wrapped: { address: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    10: {
        wrapped: { address: "0x4200000000000000000000000000000000000006" },
        name: "Optimism",
        chain: "ETH-O",
        rpcUrls: { default: "https://mainnet.optimism.io/" },
        rpc: ["https://mainnet.optimism.io/"],
        faucets: [],
        nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
        infoURL: "https://optimism.io",
        shortName: "oeth",
        chainId: 10,
        networkId: 10,
        explorers: [
            {
                name: "etherscan",
                url: "https://optimistic.etherscan.io",
                standard: "EIP3091",
            },
        ],
        blockExplorers: {
            default: {
                name: "etherscan",
                url: "https://optimistic.etherscan.io",
                standard: "EIP3091",
            },
        },
        id: 10,
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    42: {
        name: "Kovan",
        title: "Ethereum Testnet Kovan",
        chain: "ETH-K",
        network: "testnet",
        rpcUrls: {
            default: "https://kovan.poa.network",
            infura: "https://kovan.infura.io/v3/${INFURA_API_KEY}",
            wss: "wss://kovan.infura.io/ws/v3/${INFURA_API_KEY}",
            ws: "ws://kovan.poa.network:8546",
        },
        rpc: [
            "https://kovan.poa.network",
            "http://kovan.poa.network:8545",
            "https://kovan.infura.io/v3/${INFURA_API_KEY}",
            "wss://kovan.infura.io/ws/v3/${INFURA_API_KEY}",
            "ws://kovan.poa.network:8546",
        ],
        faucets: [
            "http://fauceth.komputing.org?chain=42&address=${ADDRESS}",
            "https://faucet.kovan.network",
            "https://gitter.im/kovan-testnet/faucet",
        ],
        nativeCurrency: { name: "Kovan Ether", symbol: "KOV", decimals: 18 },
        explorers: [
            {
                name: "etherscan",
                url: "https://kovan.etherscan.io",
                standard: "EIP3091",
            },
        ],
        blockExplorers: {
            default: {
                name: "etherscan",
                url: "https://kovan.etherscan.io",
                standard: "EIP3091",
            },
        },
        infoURL: "https://kovan-testnet.github.io/website",
        shortName: "kov",
        chainId: 42,
        networkId: 42,
        id: 42,
        wrapped: { address: "0xf3a6679b266899042276804930b3bfbaf807f15b" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    56: {
        name: "Binance Smart Chain Mainnet",
        chain: "BSC",
        rpcUrls: { default: "https://bsc-dataseed1.binance.org" },
        iconUrl: "https://cryptologos.cc/logos/bnb-bnb-logo.png?v=023",
        rpc: [
            "https://bsc-dataseed1.binance.org",
            "https://bsc-dataseed2.binance.org",
            "https://bsc-dataseed3.binance.org",
            "https://bsc-dataseed4.binance.org",
            "https://bsc-dataseed1.defibit.io",
            "https://bsc-dataseed2.defibit.io",
            "https://bsc-dataseed3.defibit.io",
            "https://bsc-dataseed4.defibit.io",
            "https://bsc-dataseed1.ninicoin.io",
            "https://bsc-dataseed2.ninicoin.io",
            "https://bsc-dataseed3.ninicoin.io",
            "https://bsc-dataseed4.ninicoin.io",
            "wss://bsc-ws-node.nariox.org",
        ],
        faucets: ["https://free-online-app.com/faucet-for-eth-evm-chains/"],
        nativeCurrency: {
            name: "Binance Chain Native Token",
            symbol: "BNB",
            decimals: 18,
        },
        infoURL: "https://www.binance.org",
        shortName: "bnb",
        chainId: 56,
        networkId: 56,
        slip44: 714,
        explorers: [
            { name: "bscscan", url: "https://bscscan.com", standard: "EIP3091" },
        ],
        blockExplorers: {
            default: {
                name: "bscscan",
                url: "https://bscscan.com",
                standard: "EIP3091",
            },
        },
        id: 56,
        wrapped: { address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    100: {
        iconUrl: "https://cryptologos.cc/logos/gnosis-gno-gno-logo.png?v=023",
        iconBackground: "#fff",
        testnet: false,
        name: "Gnosis Chain",
        chain: "GNO",
        rpcUrls: { default: "https://rpc.gnosischain.com" },
        rpc: [
            "https://rpc.gnosischain.com",
            "https://rpc.ankr.com/gnosis",
            "https://gnosischain-rpc.gateway.pokt.network",
            "https://gnosis-mainnet.public.blastapi.io",
            "wss://rpc.gnosischain.com/wss",
        ],
        faucets: [
            "https://faucet.gimlu.com/gnosis",
            "https://stakely.io/faucet/gnosis-chain-xdai",
            "https://faucet.prussia.dev/xdai",
        ],
        nativeCurrency: { name: "xDAI", symbol: "xDAI", decimals: 18 },
        infoURL: "https://developers.gnosischain.com",
        shortName: "gno",
        chainId: 100,
        networkId: 100,
        slip44: 700,
        explorers: [
            {
                name: "blockscout",
                url: "https://blockscout.com/xdai/mainnet",
                icon: "blockscout",
                standard: "EIP3091",
            },
        ],
        blockExplorers: {
            default: {
                name: "blockscout",
                url: "https://blockscout.com/xdai/mainnet",
                icon: "blockscout",
                standard: "EIP3091",
            },
        },
        id: 100,
        wrapped: { address: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    128: {
        name: "Huobi ECO Chain Mainnet",
        chain: "Heco",
        iconUrl:
            "https://seeklogo.com/images/H/heco-logo-B2DCC2EA11-seeklogo.com.png",
        rpcUrls: { default: "https://http-mainnet.hecochain.com" },
        rpc: [
            "https://http-mainnet.hecochain.com",
            "wss://ws-mainnet.hecochain.com",
        ],
        faucets: ["https://free-online-app.com/faucet-for-eth-evm-chains/"],
        nativeCurrency: {
            name: "Huobi ECO Chain Native Token",
            symbol: "HT",
            decimals: 18,
        },
        infoURL: "https://www.hecochain.com",
        shortName: "heco",
        chainId: 128,
        networkId: 128,
        slip44: 1010,
        explorers: [
            { name: "hecoinfo", url: "https://hecoinfo.com", standard: "EIP3091" },
        ],
        blockExplorers: {
            default: {
                name: "hecoinfo",
                url: "https://hecoinfo.com",
                standard: "EIP3091",
            },
        },
        id: 128,
        wrapped: { address: "0x5545153ccfca01fbd7dd11c0b23ba694d9509a6f" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    137: {
        name: "Polygon Mainnet",
        chain: "Polygon",
        rpcUrls: { default: "https://polygon-rpc.com/" },
        rpc: [
            "https://polygon-rpc.com/",
            "https://rpc-mainnet.matic.network",
            "https://matic-mainnet.chainstacklabs.com",
            "https://rpc-mainnet.maticvigil.com",
            "https://rpc-mainnet.matic.quiknode.pro",
            "https://matic-mainnet-full-rpc.bwarelabs.com",
        ],
        faucets: [],
        nativeCurrency: { name: "MATIC", symbol: "MATIC", decimals: 18 },
        infoURL: "https://polygon.technology/",
        shortName: "MATIC",
        chainId: 137,
        networkId: 137,
        slip44: 966,
        explorers: [
            {
                name: "polygonscan",
                url: "https://polygonscan.com",
                standard: "EIP3091",
            },
        ],

        blockExplorers: {
            default: {
                name: "polygonscan",
                url: "https://polygonscan.com",
                standard: "EIP3091",
            },
        },
        id: 137,
        wrapped: { address: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    250: {
        name: "Fantom Opera",
        chain: "FTM",
        iconUrl: "https://cryptologos.cc/logos/fantom-ftm-logo.png?v=023",
        rpcUrls: { default: "https://rpc.ftm.tools" },
        rpc: ["https://rpc.ftm.tools"],
        faucets: ["https://free-online-app.com/faucet-for-eth-evm-chains/"],
        nativeCurrency: { name: "Fantom", symbol: "FTM", decimals: 18 },
        infoURL: "https://fantom.foundation",
        shortName: "ftm",
        chainId: 250,
        networkId: 250,
        icon: "fantom",
        explorers: [
            {
                name: "ftmscan",
                url: "https://ftmscan.com",
                icon: "ftmscan",
                standard: "EIP3091",
            },
        ],
        blockExplorers: {
            default: {
                name: "ftmscan",
                url: "https://ftmscan.com",
                icon: "ftmscan",
                standard: "EIP3091",
            },
        },
        wrapped: { address: "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83" },
        id: 250,
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    // 787: {
    //   name: "Acala Network",
    //   chain: "ACA",
    //   iconUrl: "https://cryptologos.cc/logos/fantom-ftm-logo.png?v=023",
    //   rpcUrls: { default: "https://eth-rpc-acala.aca-api.network" },
    //   rpc: ["https://eth-rpc-acala.aca-api.network"],
    //   nativeCurrency: { name: "ACALA", symbol: "ACA", decimals: 18 },
    //   shortName: "aca",
    //   chainId: 787,
    //   networkId: 787,
    //   icon: "aca",
    //   explorers: [
    //     {
    //       name: "acala-scanner",
    //       url: "https://blockscout.acala.network",
    //     },
    //   ],
    //   blockExplorers: {
    //     default: {
    //       name: "acala-scanner",
    //       url: "https://blockscout.acala.network",
    //     }
    //   },
    //   wrapped: { address: "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83" },
    //   id: 787,
    //   multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    // },
    42161: {
        name: "Arbitrum One",
        chainId: 42161,
        shortName: "arb1",
        chain: "ETH-A",
        networkId: 42161,
        nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
        rpcUrls: { default: "https://arb1.arbitrum.io/rpc" },
        rpc: [
            "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}",
            "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
            "https://arb1.arbitrum.io/rpc",
        ],
        faucets: [],
        explorers: [
            { name: "Arbiscan", url: "https://arbiscan.io", standard: "EIP3091" },
            {
                name: "Arbitrum Explorer",
                url: "https://explorer.arbitrum.io",
                standard: "EIP3091",
            },
        ],
        blockExplorers: {
            default: {
                name: "Arbiscan",
                url: "https://arbiscan.io",
                standard: "EIP3091",
            },
        },
        infoURL: "https://arbitrum.io",
        parent: {
            type: "L2",
            chain: "eip155-1",
            bridges: [{ url: "https://bridge.arbitrum.io" }],
        },
        wrapped: { address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" },
        id: 42161,
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    42220: {
        name: "Celo Mainnet",
        chainId: 42220,
        shortName: "CELO",
        chain: "CELO",
        iconUrl: "https://cryptologos.cc/logos/celo-celo-logo.png?v=023",
        networkId: 42220,
        nativeCurrency: { name: "CELO", symbol: "CELO", decimals: 18 },
        rpcUrls: {
            default: "https://forno.celo.org",
            wss: "wss://forno.celo.org/ws",
        },
        rpc: ["https://forno.celo.org", "wss://forno.celo.org/ws"],
        faucets: ["https://free-online-app.com/faucet-for-eth-evm-chains/"],
        infoURL: "https://docs.celo.org/",
        explorers: [
            {
                name: "blockscout",
                url: "https://explorer.celo.org",
                standard: "none",
            },
        ],
        blockExplorers: {
            default: {
                name: "blockscout",
                url: "https://explorer.celo.org",
                standard: "none",
            },
        },
        id: 42220,
        wrapped: { address: "0x3Ad443d769A07f287806874F8E5405cE3Ac902b9" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    43114: {
        name: "Avalanche C-Chain",
        chain: "AVAX",
        rpcUrls: { default: "https://api.avax.network/ext/bc/C/rpc" },
        rpc: ["https://api.avax.network/ext/bc/C/rpc"],
        faucets: ["https://free-online-app.com/faucet-for-eth-evm-chains/"],
        nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
        infoURL: "https://www.avax.network/",
        shortName: "Avalanche",
        chainId: 43114,
        networkId: 43114,
        slip44: 9005,
        explorers: [
            { name: "snowtrace", url: "https://snowtrace.io", standard: "EIP3091" },
        ],
        blockExplorers: {
            default: {
                name: "snowtrace",
                url: "https://snowtrace.io",
                standard: "EIP3091",
            },
        },
        wrapped: { address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7" },
        id: 43114,
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
    11155111: {
        name: "Sepolia",
        title: "Ethereum Testnet Sepolia",
        chain: "ETH-S",
        network: "testnet",
        rpcUrls: {
            public: "https://rpc.sepolia.org",
            default: "https://rpc.sepolia.online",
        },
        rpc: ["https://rpc.sepolia.org", "https://rpc.sepolia.online"],
        faucets: [
            "http://fauceth.komputing.org?chain=5&address=${ADDRESS}",
            "https://goerli-faucet.slock.it?address=${ADDRESS}",
            "https://faucet.goerli.mudit.blog",
        ],
        nativeCurrency: { name: "SEP Ether", symbol: "SEP", decimals: 18 },
        infoURL: "https://goerli.net/#about",
        shortName: "sep",
        chainId: 11155111,
        networkId: 11155111,
        ens: { registry: "0x112234455c3a32fd11230c42e7bccd4a84e02010" },
        explorers: [
            {
                name: "etherscan-sepolia",
                url: "https://sepolia.etherscan.io/",
                standard: "EIP3091",
            },
        ],
        blockExplorers: {
            default: {
                name: "etherscan-sepolia",
                url: "https://sepolia.etherscan.io/",
                standard: "EIP3091",
            },
        },
        id: 11155111,
        wrapped: { address: "0xf531b8f309be94191af87605cfbf600d71c2cfe0" },
        multicall: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
    },
};
